## config for the style and content image
style_image: ../../eval/style/starry.jpg # the style image we want to train
data_dir: ../../content # the content image folders
model_dir: ../../starry_models # dirs to save the model
feature_path: ../../vgg/vgg16.npy # the pre-trained vgg16 model


## below can be fixed if you do not know how to change them
## Loss Network
content_layers:
  - "conv3_3"
style_layers:
  - "conv1_2"
  - "conv2_2"
  - "conv3_3"
  - "conv4_3"
style_weight: 220.0
content_weight: 1.0
tv_weight: 0


## learning params
image_size: 256
batch_size: 4
mean: [123.68, 116.779, 103.939]
lr: 0.001
max_iter: 40000
display: 10
snapshot: 5000
finetune: False



